### ISSUE TITLE
Support 'optional' fields?

### ISSUE THREAD

**Issue by NicolasT** [awakesecurity/proto3-suite#27]
I'm using `grpc-haskell` in some project, and needed to use `optional` fields in some `Message` (to emulate a tagged union). It seems like `compile-proto-file` doesn't grok this (or my proto file is invalid?):

```proto
syntax = "proto3";
package test;

message M {
        optional uint64 i = 0;
}
```

```
stack exec -- compile-proto-file --proto foo.proto --out .
Error: failed to compile "foo.proto":

CompileParseError (line 5, column 25):
unexpected "i"
expecting "="
```

Am I doing something wrong, or (if not) are there any plans to support such fields?

**Comment by Gabriel439** [comment]
@NicolasT: In protocol buffers version 3 all fields are already "optional", although optional in this context means something different

First off, a "scalar" field is basically any field that is not a message (i.e. an `int` or `string` is a scalar field).  Since all fields are optional, that means that all scalar fields are optional and can be missing from messages.  However the protocol buffers 3 specification mandates that the semantics of a missing scalar field is to default that field to a specific value (such as `0` for `int`, `""` for `string` or `false` for `bool`).  We're not allowed to wrap these scalar fields in a `Maybe` when emitting the code for the matching Haskell type.

However, you message fields are also optional and these sorts of fields do translate to Haskell types wrapped in `Maybe`.  That means that if the message field is present then you get the decoded message wrapped in `Just` and if the message field is absent then you get `Nothing`

So, to answer your question, protocol buffers 3 does support optional fields in the Haskell sense of the word (i.e. fields wrapped `Maybe` and not fields with a default), but only if you wrap them in a record with 1 field.

In other words, for your example, if you wanted the generated Haskell code to wrap the `i` field of the `message` `M` in a `Maybe` then you would need to change your definition to this:

```proto
syntax = "proto3";
package test;

message M {
        UInt64Value i = 0;
}

message UInt64Value {
  uint64 value = 1;
}
```

... and then the generated Haskell code would look something like this:

```haskell
newtype M = M { i :: Maybe UInt64Value }

newtype UInt64Value = UInt64Value { value :: Word64 }
```

You might wonder: is there a way to get the Haskell code generator to emit the `Maybe` without wrapping the `Word64` in a newtype?  The answer is "no" and I believe this is true for other code generators (correct me if I'm wrong)

Also, this pattern of wrapping fields in 1-field messages to get `Maybe` semantics is so common that the `google/protobuf` repository has a set of standard wrappers exactly for this purpose.  You can find those wrappers here:

https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto

**Comment by NicolasT** [comment]
@Gabriel439 Thanks for the thorough explanation (as always when coming from you :wink:). Seems like I made assumptions I shouldn't have made!

**Comment by Gabriel439** [comment]
@NicolasT: You're welcome! :)
